apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployboard-backend
  namespace: deployboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployboard-backend
  template:
    metadata:
      labels:
        app: deployboard-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/kaan-yassibas/deployboard-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: STORAGE_BACKEND
              value: "dynamodb"
            - name: AWS_REGION
              value: "eu-north-1"
            - name: DYNAMODB_MONITORS_TABLE
              value: "deployboard-monitors"
            - name: DYNAMODB_CHECKS_TABLE
              value: "deployboard-checks"
            - name: DYNAMODB_INCIDENTS_TABLE
              value: "deployboard-incidents"